# Generated by Django 4.2.2 on 2023-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectlink',
            name='short_code',
            field=models.SlugField(blank=True, max_length=8, verbose_name='Короткий код, добавляеый к ссылке'),
        ),
    ]
