# Generated by Django 4.2.2 on 2023-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_alter_redirectlink_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectlink',
            name='rdir_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во переходов'),
        ),
        migrations.AlterField(
            model_name='redirectlink',
            name='short_code',
            field=models.SlugField(blank=True, max_length=8, null=True, verbose_name='Короткий код, добавляеый к ссылке'),
        ),
    ]
